# cloudbuild.yaml
steps:
# Paso 1: Construir la imagen de Docker.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '--no-cache'
  - '-t'
  - 'gcr.io/$PROJECT_ID/pida-rag-api:$COMMIT_SHA'
  - '.'

# Paso 2: Subir la imagen construida al Container Registry de Google.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/pida-rag-api:$COMMIT_SHA'

# Paso 3: Desplegar la imagen desde el Container Registry a Cloud Run.
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args:
  - 'run'
  - 'deploy'
  - 'pida-rag-api'
  - '--image=gcr.io/$PROJECT_ID/pida-rag-api:$COMMIT_SHA'
  - '--region=us-central1'
  - '--allow-unauthenticated'
  - '--service-account=pida-indexer-sa@pida-470320.iam.gserviceaccount.com'
  # Referencia a las variables de entorno que son secretos
  - '--update-secrets=LANGCHAIN_GOOGLE_GEMINI_API_KEY=gemini-api-key:latest'
  # --- VARIABLES DE ENTORNO ACTUALIZADAS Y COMPLETAS ---
  # IMPORTANTE: Reemplaza la URL con la URL real de tu servicio Cloud Run una vez desplegado.
  # Usa el ID de la cola que creaste en el Paso 1 (ej: pdf-processing-queue).
  - '--update-env-vars=PROJECT_ID=pida-470320,VERTEX_AI_LOCATION=us-central1,TASK_QUEUE_ID=pdf-processing-queue,CLOUD_RUN_URL=https://pida-rag-api-q54fi7z3ka-uc.a.run.app'

# Especifica la imagen que se ha subido como resultado de esta construcción.
images:
- 'gcr.io/$PROJECT_ID/pida-rag-api:$COMMIT_SHA'
